# Generated by Django 4.2 on 2023-05-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task5', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='goals_conceded',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='club',
            name='goals_scored',
            field=models.IntegerField(default=0),
        ),
    ]
