# Generated by Django 4.2 on 2023-05-06 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task5', '0002_club_goals_conceded_club_goals_scored'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='legue',
            name='club_limits',
        ),
        migrations.AddField(
            model_name='player',
            name='all_goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='club',
            name='lague',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='legues', to='task5.legue'),
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asistent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asists', to='task5.player')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='task5.player')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='legue',
            name='season',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='legues', to='task5.season'),
            preserve_default=False,
        ),
    ]
